### ISSUE TITLE
Why not use a locally installed tidy?

### ISSUE THREAD

**Issue by dennisguse** [gavinballard/grunt-htmltidy#5]
If I saw it correctly, tidy is downloaded via npm.
This is actually unnecessary if a local tidy is installed...

**Comment by gavinballard** [comment]
We rely on the `htmltidy` NPM package, which exposes `tidy` via Javascript, so if you were really concerned about using a local tidy if available then I think that would be the place to do that. If there's a better alternative for this gem, Pull Requests welcome but this won't be something I look into in any detail.
